// AUTO-GENERATED by scripts/make_challenge.py — do not edit by hand.
// Regenerate with:  python3 scripts/make_challenge.py
import type { Challenge } from "./design";

export const GENERATED_CHALLENGES: Challenge[] = [
  {
    "id": "gen-empty-0-8735",
    "title": "THE BLANK PAGE",
    "brief": "You've got a blank canvas, a traffic forecast, and a finance team watching the meter. Target: 332,000 users (~33,200 req/s) for under $76,000/month.",
    "budget": 76000,
    "users": 332000,
    "requireNoSpof": false,
    "start": "empty",
    "generated": true,
    "nodes": [],
    "edges": []
  },
  {
    "id": "gen-empty-1-5071",
    "title": "SHIP IT",
    "brief": "Nothing exists yet. Wire up something that holds \u2014 you're paying for every box you place. Target: 539,000 users (~53,900 req/s) for under $129,000/month.",
    "budget": 129000,
    "users": 539000,
    "requireNoSpof": false,
    "start": "empty",
    "generated": true,
    "nodes": [],
    "edges": []
  },
  {
    "id": "gen-empty-2-2430",
    "title": "VIRAL FRIDAY",
    "brief": "New project, new cloud bill starting at zero. Every component you add moves the needle. Target: 34,000 users (~3,400 req/s) for under $8,000/month.",
    "budget": 8000,
    "users": 34000,
    "requireNoSpof": false,
    "start": "empty",
    "generated": true,
    "nodes": [],
    "edges": []
  },
  {
    "id": "gen-empty-3-7633",
    "title": "NO BUDGET, ALL VIBES",
    "brief": "New project, new cloud bill starting at zero. Every component you add moves the needle. Target: 739,000 users (~73,900 req/s) for under $199,000/month.",
    "budget": 199000,
    "users": 739000,
    "requireNoSpof": false,
    "start": "empty",
    "generated": true,
    "nodes": [],
    "edges": []
  },
  {
    "id": "gen-empty-4-5332",
    "title": "GREENFIELD",
    "brief": "Nothing exists yet. Wire up something that holds \u2014 you're paying for every box you place. Target: 362,000 users (~36,200 req/s) for under $93,000/month.",
    "budget": 93000,
    "users": 362000,
    "requireNoSpof": false,
    "start": "empty",
    "generated": true,
    "nodes": [],
    "edges": []
  },
  {
    "id": "gen-empty-5-0663",
    "title": "VIRAL FRIDAY",
    "brief": "Nothing exists yet. Wire up something that holds \u2014 you're paying for every box you place. Target: 31,000 users (~3,100 req/s) for under $8,000/month.",
    "budget": 8000,
    "users": 31000,
    "requireNoSpof": false,
    "start": "empty",
    "generated": true,
    "nodes": [],
    "edges": []
  },
  {
    "id": "gen-broken-6-9341",
    "title": "TRAFFIC SPIKE",
    "brief": "One component is dying and taking everything with it. Find it and fix it. Target: 403,000 users (~40,300 req/s) for under $109,000/month. No single point of failure allowed.",
    "budget": 109000,
    "users": 403000,
    "requireNoSpof": true,
    "start": "broken",
    "generated": true,
    "nodes": [
      {
        "id": "u",
        "kind": "client",
        "x": 120,
        "y": 260
      },
      {
        "id": "api",
        "kind": "api",
        "x": 460,
        "y": 260
      },
      {
        "id": "db",
        "kind": "database",
        "x": 800,
        "y": 260
      }
    ],
    "edges": [
      {
        "id": "u->api",
        "from": "u",
        "to": "api",
        "mode": "read"
      },
      {
        "id": "api->db",
        "from": "api",
        "to": "db",
        "mode": "write"
      }
    ]
  },
  {
    "id": "gen-broken-7-3867",
    "title": "TRAFFIC SPIKE",
    "brief": "This design melts under load. Fix it without rebuilding from scratch \u2014 and stay under budget. Target: 57,000 users (~5,700 req/s) for under $13,000/month.",
    "budget": 13000,
    "users": 57000,
    "requireNoSpof": false,
    "start": "broken",
    "generated": true,
    "nodes": [
      {
        "id": "u",
        "kind": "client",
        "x": 120,
        "y": 260
      },
      {
        "id": "api",
        "kind": "api",
        "x": 460,
        "y": 260
      },
      {
        "id": "db",
        "kind": "database",
        "x": 800,
        "y": 260
      }
    ],
    "edges": [
      {
        "id": "u->api",
        "from": "u",
        "to": "api",
        "mode": "read"
      },
      {
        "id": "api->db",
        "from": "api",
        "to": "db",
        "mode": "write"
      }
    ]
  },
  {
    "id": "gen-broken-8-6345",
    "title": "SWEATING BULLETS",
    "brief": "One component is dying and taking everything with it. Find it and fix it. Target: 41,000 users (~4,100 req/s) for under $10,000/month.",
    "budget": 10000,
    "users": 41000,
    "requireNoSpof": false,
    "start": "broken",
    "generated": true,
    "nodes": [
      {
        "id": "u",
        "kind": "client",
        "x": 120,
        "y": 260
      },
      {
        "id": "api",
        "kind": "api",
        "x": 460,
        "y": 260
      },
      {
        "id": "db",
        "kind": "database",
        "x": 800,
        "y": 260
      }
    ],
    "edges": [
      {
        "id": "u->api",
        "from": "u",
        "to": "api",
        "mode": "read"
      },
      {
        "id": "api->db",
        "from": "api",
        "to": "db",
        "mode": "write"
      }
    ]
  },
  {
    "id": "gen-broken-9-5436",
    "title": "SWEATING BULLETS",
    "brief": "This design melts under load. Fix it without rebuilding from scratch \u2014 and stay under budget. Target: 35,000 users (~3,500 req/s) for under $10,000/month.",
    "budget": 10000,
    "users": 35000,
    "requireNoSpof": false,
    "start": "broken",
    "generated": true,
    "nodes": [
      {
        "id": "u",
        "kind": "client",
        "x": 120,
        "y": 260
      },
      {
        "id": "api",
        "kind": "api",
        "x": 460,
        "y": 260
      },
      {
        "id": "db",
        "kind": "database",
        "x": 800,
        "y": 260
      }
    ],
    "edges": [
      {
        "id": "u->api",
        "from": "u",
        "to": "api",
        "mode": "read"
      },
      {
        "id": "api->db",
        "from": "api",
        "to": "db",
        "mode": "write"
      }
    ]
  },
  {
    "id": "gen-broken-10-2468",
    "title": "SWEATING BULLETS",
    "brief": "This design melts under load. Fix it without rebuilding from scratch \u2014 and stay under budget. Target: 142,000 users (~14,200 req/s) for under $31,000/month.",
    "budget": 31000,
    "users": 142000,
    "requireNoSpof": false,
    "start": "broken",
    "generated": true,
    "nodes": [
      {
        "id": "u",
        "kind": "client",
        "x": 120,
        "y": 260
      },
      {
        "id": "api",
        "kind": "api",
        "x": 460,
        "y": 260
      },
      {
        "id": "db",
        "kind": "database",
        "x": 800,
        "y": 260
      }
    ],
    "edges": [
      {
        "id": "u->api",
        "from": "u",
        "to": "api",
        "mode": "read"
      },
      {
        "id": "api->db",
        "from": "api",
        "to": "db",
        "mode": "write"
      }
    ]
  },
  {
    "id": "gen-empty-11-7555",
    "title": "ZERO TO HERO",
    "brief": "Nothing exists yet. Wire up something that holds \u2014 you're paying for every box you place. Target: 19,000 users (~1,900 req/s) for under $5,000/month. No single point of failure allowed.",
    "budget": 5000,
    "users": 19000,
    "requireNoSpof": true,
    "start": "empty",
    "generated": true,
    "nodes": [],
    "edges": []
  },
  {
    "id": "gen-broken-12-1160",
    "title": "THE 3AM PAGE",
    "brief": "This design melts under load. Fix it without rebuilding from scratch \u2014 and stay under budget. Target: 80,000 users (~8,000 req/s) for under $22,000/month.",
    "budget": 22000,
    "users": 80000,
    "requireNoSpof": false,
    "start": "broken",
    "generated": true,
    "nodes": [
      {
        "id": "u",
        "kind": "client",
        "x": 120,
        "y": 260
      },
      {
        "id": "api",
        "kind": "api",
        "x": 460,
        "y": 260
      },
      {
        "id": "db",
        "kind": "database",
        "x": 800,
        "y": 260
      }
    ],
    "edges": [
      {
        "id": "u->api",
        "from": "u",
        "to": "api",
        "mode": "read"
      },
      {
        "id": "api->db",
        "from": "api",
        "to": "db",
        "mode": "write"
      }
    ]
  },
  {
    "id": "gen-empty-13-8113",
    "title": "THE BIG BET",
    "brief": "An empty account and a load target. Build the whole thing yourself and stay inside your budget. Target: 25,000 users (~2,500 req/s) for under $7,000/month.",
    "budget": 7000,
    "users": 25000,
    "requireNoSpof": false,
    "start": "empty",
    "generated": true,
    "nodes": [],
    "edges": []
  }
];
