import {
  CATALOG,
  instancedUnits,
  provisionCapacity,
  shortName,
  type Edge,
  type FlowNode,
  type NodeKind,
  type Sim,
} from "./design";

/* ============================================================
   INFRASTRUCTURE AS CODE — turn the diagram into something real
   ============================================================ */

/** how many catalog-sized instances the current design provisions */
function instanceCount(kind: NodeKind, capacity: number) {
  return Math.max(1, Math.round(instancedUnits(kind, capacity)));
}

const isEdgeOnly = (k: NodeKind) =>
  k === "client" || k === "browser" || k === "mobile" || k === "iot";

/* ---------------- docker-compose ---------------- */

const IMAGES: Partial<Record<NodeKind, string>> = {
  api: "node:20-alpine",
  microservice: "node:20-alpine",
  bff: "node:20-alpine",
  graphql: "node:20-alpine",
  container: "node:20-alpine",
  serverless: "node:20-alpine",
  worker: "node:20-alpine",
  scheduler: "node:20-alpine",
  database: "postgres:16",
  replica: "postgres:16",
  shard: "postgres:16",
  nosql: "mongo:7",
  cache: "redis:7-alpine",
  queue: "rabbitmq:3-management",
  eventbus: "rabbitmq:3-management",
  dlq: "rabbitmq:3-management",
  pubsub: "nats:2",
  stream: "nats:2",
  search: "docker.elastic.co/elasticsearch/elasticsearch:8.13.0",
  timeseries: "influxdb:2",
  vectordb: "qdrant/qdrant",
  warehouse: "clickhouse/clickhouse-server",
  lake: "minio/minio",
  objectstore: "minio/minio",
  loadbalancer: "nginx:alpine",
  proxy: "nginx:alpine",
  gateway: "nginx:alpine",
  region: "nginx:alpine",
  cdn: "nginx:alpine",
  waf: "nginx:alpine",
  dns: "coredns/coredns",
  auth: "node:20-alpine",
  ratelimit: "envoyproxy/envoy:distroless",
  circuit: "envoyproxy/envoy:distroless",
  config: "hashicorp/consul:1.19",
  registry: "hashicorp/consul:1.19",
  secrets: "hashicorp/vault:1.17",
  monitoring: "prom/prometheus",
  logging: "grafana/loki:3.0.0",
  tracing: "jaegertracing/all-in-one",
  payment: "node:20-alpine",
  notify: "node:20-alpine",
  model: "ghcr.io/huggingface/text-generation-inference:latest",
  embedding: "ghcr.io/huggingface/text-embeddings-inference:latest",
  rag: "node:20-alpine",
  gpu: "nvidia/cuda:12.4.0-base-ubuntu22.04",
};

function svcName(n: FlowNode, nodes: FlowNode[]) {
  const sameKind = nodes.filter((x) => x.kind === n.kind);
  const idx = sameKind.findIndex((x) => x.id === n.id);
  const base = n.kind.replace(/[^a-z0-9]/gi, "-");
  return sameKind.length > 1 ? `${base}-${idx + 1}` : base;
}

export function toDockerCompose(
  nodes: FlowNode[],
  edges: Edge[],
  sim: Sim,
): string {
  const services = nodes.filter((n) => !isEdgeOnly(n.kind));
  if (!services.length) return "# nothing to run — add some components first\n";

  const nameOf = new Map(nodes.map((n) => [n.id, svcName(n, nodes)]));
  const lines: string[] = [
    "# Generated by Flow Studio — http://localhost:3000",
    `# ${nodes.length} components · ${edges.length} links`,
    "services:",
  ];

  for (const n of services) {
    const entry = CATALOG[n.kind];
    const sn = sim.nodes[n.id];
    const image = IMAGES[n.kind] ?? "alpine:latest";
    const cap = sn?.capacity ?? entry.capacity;
    const count = cap === Infinity ? 1 : instanceCount(n.kind, cap);
    const name = nameOf.get(n.id)!;
    lines.push(`  ${name}:`);
    lines.push(`    image: ${image}`);
    lines.push(`    # ${shortName(n.kind)} · ${entry.tagline}`);
    if (count > 1) lines.push(`    deploy:`);
    if (count > 1) lines.push(`      replicas: ${count}`);
    const down = edges
      .filter((e) => e.from === n.id)
      .map((e) => nameOf.get(e.to))
      .filter(Boolean) as string[];
    if (down.length) {
      lines.push(`    depends_on:`);
      for (const d of Array.from(new Set(down))) lines.push(`      - ${d}`);
    }
    if (n.kind === "database" || n.kind === "replica" || n.kind === "shard") {
      lines.push(`    environment:`);
      lines.push(`      POSTGRES_PASSWORD: \${DB_PASSWORD:-changeme}`);
    }
    if (n.kind === "gpu" || n.kind === "model") {
      lines.push(`    deploy:`);
      lines.push(`      resources:`);
      lines.push(`        reservations:`);
      lines.push(`          devices:`);
      lines.push(`            - capabilities: [gpu]`);
    }
    lines.push("");
  }

  lines.push("# internal network so services resolve each other by name");
  lines.push("networks:");
  lines.push("  default:");
  lines.push("    driver: bridge");
  return lines.join("\n");
}

/* ---------------- terraform ---------------- */

interface TfMap {
  resource: string;
  attrs: string[];
}

const TF: Partial<Record<NodeKind, TfMap>> = {
  api: { resource: "aws_ecs_service", attrs: ['launch_type = "FARGATE"'] },
  microservice: { resource: "aws_ecs_service", attrs: [] },
  bff: { resource: "aws_ecs_service", attrs: [] },
  graphql: { resource: "aws_ecs_service", attrs: [] },
  container: { resource: "aws_ecs_service", attrs: [] },
  worker: { resource: "aws_ecs_service", attrs: [] },
  rag: { resource: "aws_ecs_service", attrs: [] },
  serverless: { resource: "aws_lambda_function", attrs: [] },
  database: { resource: "aws_db_instance", attrs: ['engine = "postgres"', "multi_az = true"] },
  shard: { resource: "aws_db_instance", attrs: ['engine = "postgres"'] },
  replica: { resource: "aws_db_instance", attrs: ["replicate_source_db = aws_db_instance.database.id"] },
  nosql: { resource: "aws_dynamodb_table", attrs: ['billing_mode = "PAY_PER_REQUEST"'] },
  cache: { resource: "aws_elasticache_cluster", attrs: ['engine = "redis"', "num_cache_nodes = 1"] },
  queue: { resource: "aws_sqs_queue", attrs: [] },
  eventbus: { resource: "aws_sqs_queue", attrs: [] },
  dlq: { resource: "aws_sqs_queue", attrs: [] },
  objectstore: { resource: "aws_s3_bucket", attrs: [] },
  lake: { resource: "aws_s3_bucket", attrs: [] },
  cdn: { resource: "aws_cloudfront_distribution", attrs: ["enabled = true"] },
  loadbalancer: { resource: "aws_lb", attrs: ['load_balancer_type = "application"'] },
  gateway: { resource: "aws_apigatewayv2_api", attrs: ['protocol_type = "HTTP"'] },
  waf: { resource: "aws_wafv2_web_acl", attrs: ['scope = "CLOUDFRONT"'] },
  dns: { resource: "aws_route53_zone", attrs: [] },
  search: { resource: "aws_opensearch_domain", attrs: [] },
  warehouse: { resource: "aws_redshift_cluster", attrs: [] },
  monitoring: { resource: "aws_cloudwatch_metric_alarm", attrs: [] },
  logging: { resource: "aws_cloudwatch_log_group", attrs: [] },
  tracing: { resource: "aws_xray_group", attrs: [] },
  secrets: { resource: "aws_secretsmanager_secret", attrs: [] },
  registry: { resource: "aws_service_discovery_service", attrs: [] },
  gpu: { resource: "aws_instance", attrs: ['instance_type = "p4d.24xlarge"'] },
  model: { resource: "aws_sagemaker_endpoint", attrs: [] },
  embedding: { resource: "aws_sagemaker_endpoint", attrs: [] },
  auth: { resource: "aws_cognito_user_pool", attrs: [] },
  config: { resource: "aws_ssm_parameter", attrs: [] },
  timeseries: { resource: "aws_timestreamwrite_database", attrs: [] },
  vectordb: { resource: "aws_opensearchserverless_collection", attrs: [] },
};

export function toTerraform(
  nodes: FlowNode[],
  edges: Edge[],
  sim: Sim,
): string {
  const services = nodes.filter((n) => !isEdgeOnly(n.kind));
  if (!services.length) return "# nothing to build — add some components first\n";

  const nameOf = new Map(nodes.map((n) => [n.id, svcName(n, nodes)]));
  const out: string[] = [
    "# Generated by Flow Studio — http://localhost:3000",
    `# ${nodes.length} components · ${edges.length} links`,
    "",
    'terraform {',
    '  required_providers {',
    '    aws = { source = "hashicorp/aws", version = "~> 5.0" }',
    "  }",
    "}",
    "",
    'provider "aws" { region = var.region }',
    "",
    'variable "region" { default = "us-east-1" }',
    "",
    "# ── resources ──",
    "",
  ];

  for (const n of services) {
    const map = TF[n.kind];
    const sn = sim.nodes[n.id];
    const cap = sn?.capacity ?? CATALOG[n.kind].capacity;
    const count = cap === Infinity ? 1 : instanceCount(n.kind, cap);
    const name = nameOf.get(n.id)!.replace(/-/g, "_");
    if (!map) {
      out.push(`# ${shortName(n.kind)} (${name}) — no direct AWS equivalent modelled`);
      out.push("");
      continue;
    }
    out.push(`resource "${map.resource}" "${name}" {`);
    for (const a of map.attrs) out.push(`  ${a}`);
    if (count > 1)
      out.push(`  # scales to ~${count} instances at current load (${Math.round(cap).toLocaleString()} rps)`);
    out.push(`  tags = { Name = "${name}" }`);
    out.push("}");
    out.push("");
  }

  out.push("# ── wiring ──");
  for (const e of edges) {
    const a = nameOf.get(e.from);
    const b = nameOf.get(e.to);
    if (a && b) out.push(`# ${a} --${e.mode}--> ${b}`);
  }
  return out.join("\n");
}

/** convenience: what capacity we'd provision for a node, for docs/exports */
export const capacityFor = (kind: NodeKind, inflow: number) =>
  provisionCapacity(kind, inflow);
