"use client";

export type Mode = "hero" | "sandbox" | "scenarios" | "challenges" | "shared";

interface CardDef {
  mode: Mode;
  glyph: string;
  title: string;
  blurb: string;
  detail: string;
  accent: string;
}

export default function ModeScreen({
  onChoose,
  scenarioCount,
  challengeCount,
}: {
  onChoose: (m: Mode) => void;
  scenarioCount: number;
  challengeCount: number;
}) {
  const cards: CardDef[] = [
    {
      mode: "hero",
      glyph: "🪙",
      title: "Zero → Hero",
      blurb: "Start with nothing.",
      detail:
        "Blank canvas, $0 in the bank, no revenue model, only free-tier components. Users arrive on their own and fund you. Pivot the business, pitch investors (it's a gamble), unlock new tiers — side project all the way to a real company.",
      accent: "var(--color-good)",
    },
    {
      mode: "sandbox",
      glyph: "🧪",
      title: "Sandbox",
      blurb: "Everything unlocked.",
      detail:
        "Empty canvas, no budget, no rules. All 51 components, plus chaos, replay, cost, latency and the IaC exports. Test whatever you want.",
      accent: "var(--color-accent)",
    },
    {
      mode: "scenarios",
      glyph: "📚",
      title: "Scenarios",
      blurb: "Learn the fundamentals.",
      detail: `${scenarioCount} guided builds that walk from "one database melts" to a full stack that holds.`,
      accent: "var(--color-accent)",
    },
    {
      mode: "challenges",
      glyph: "⚔",
      title: "Challenges",
      blurb: "Get graded.",
      detail: `${challengeCount} scored puzzles — repair a melting design or build one from scratch, with a budget and a goal.`,
      accent: "var(--color-warn)",
    },
  ];

  return (
    <div className="dotgrid flex min-h-screen w-full flex-col items-center justify-center overflow-y-auto px-6 py-10">
      <div className="w-full max-w-4xl">
        <div className="mb-8">
          <div className="mono text-[10px] uppercase tracking-[0.3em] text-[var(--color-accent)]">
            flow studio
          </div>
          <h1 className="mt-2 text-[34px] font-extrabold leading-tight tracking-tight text-[var(--color-ink)]">
            Link components. See how it holds.
          </h1>
          <p className="mt-2 max-w-2xl text-[13.5px] leading-relaxed text-[var(--color-muted)]">
            A system-design playground. Wire up infrastructure, crank the traffic,
            and find out what breaks — what it costs, how slow it feels, and
            whether it survives losing a box.
          </p>
          <div className="mono mt-3 text-[11px] text-[var(--color-muted)]">
            Pick how you want to start ↓
          </div>
        </div>

        <div className="grid gap-3 sm:grid-cols-2">
          {cards.map((c) => (
            <button
              key={c.mode}
              onClick={() => onChoose(c.mode)}
              className="panel group flex flex-col rounded-2xl p-5 text-left transition hover:-translate-y-0.5"
              style={{ borderColor: "var(--color-line)" }}
            >
              <div className="flex items-center gap-2.5">
                <span
                  className="grid h-9 w-9 shrink-0 place-items-center rounded-xl text-[18px]"
                  style={{
                    background: `color-mix(in srgb, ${c.accent} 14%, transparent)`,
                  }}
                >
                  {c.glyph}
                </span>
                <div>
                  <div className="text-[16px] font-bold leading-tight text-[var(--color-ink)]">
                    {c.title}
                  </div>
                  <div
                    className="mono text-[10px] uppercase tracking-wide"
                    style={{ color: c.accent }}
                  >
                    {c.blurb}
                  </div>
                </div>
              </div>
              <p className="mt-3 text-[12px] leading-relaxed text-[var(--color-muted)]">
                {c.detail}
              </p>
              <div
                className="mono mt-4 text-[10px] font-bold"
                style={{ color: c.accent }}
              >
                start →
              </div>
            </button>
          ))}
        </div>

        <div className="mono mt-6 text-[10px] leading-relaxed text-[var(--color-muted)]">
          New puzzles are generated by{" "}
          <span className="text-[var(--color-ink)]">scripts/make_challenge.py</span>{" "}
          — run it to add more targets. Everything runs in your browser; nothing
          is uploaded anywhere.
        </div>
      </div>
    </div>
  );
}
